// SPDX-License-Identifier: MIT OR Apache-2.0
// DO NOT EDIT — generated by `cargo run -p xtask -- ffi-headers`
// Graph PDE C ABI for semiflow-core (v2.2, ADR-0059).
//
// This header exposes the graph-PDE entry points: Graph, GraphSignal,
// GraphHeatChernoff (GHC), and MagnusGraphHeatChernoff (MGHC).
// All types, status codes, and error values are shared with `semiflow.h`.
//
// Usage:
//   #include "semiflow_graph.h"   // includes semiflow.h automatically
//
// Build requirement:
//   Link against the cdylib built with `--profile release-ffi`:
//     cargo build -p semiflow-ffi --profile release-ffi
//   The binary is at target/release-ffi/libsemiflow_ffi.{so,dylib,dll}.

#pragma once

#ifndef SEMIFLOW_GRAPH_H
#define SEMIFLOW_GRAPH_H

#include "semiflow.h"

#ifdef __cplusplus
extern "C" {
#endif

/*---------------------------------------------------------------------------*/
/* Opaque handle types                                                        */
/*---------------------------------------------------------------------------*/

/* Opaque handle to a Graph<f64>.
 * Allocate with smf_graph_path; free with smf_graph_drop. */
/* typedef struct SmfGraph SmfGraph;  -- defined in semiflow.h */

/* Opaque handle to a GraphSignal<f64>.
 * Allocate with smf_graphsig_new; free with smf_graphsig_drop. */
/* typedef struct SmfGraphSig SmfGraphSig;  -- defined in semiflow.h */

/* Opaque handle to a GraphHeatChernoff state.
 * Allocate with smf_ghc_new; free with smf_ghc_drop. */
/* typedef struct SmfGhc SmfGhc;  -- defined in semiflow.h */

/* Opaque handle to a MagnusGraphHeatChernoff state.
 * Allocate with smf_mghc_new; free with smf_mghc_drop. */
/* typedef struct SmfMghc SmfMghc;  -- defined in semiflow.h */

/*---------------------------------------------------------------------------*/
/* LaplacianAtTime callback                                                   */
/*---------------------------------------------------------------------------*/

/**
 * Callback type for time-dependent Laplacian construction.
 *
 * The callback receives:
 *   t          — sample time (seconds).
 *   user_data  — opaque pointer supplied to smf_mghc_new.
 *   out_graph  — output: set *out_graph to a freshly allocated SmfGraph*.
 *
 * The callback MUST:
 * - Be pure: same `t` → same topology + weights.
 * - Preserve edge topology (row_ptr/col_idx) of the base graph.
 * - Return 0 on success; non-zero on error.
 * - NOT throw C++ exceptions across the boundary (UB).
 *
 * The Rust side takes ownership of *out_graph after the callback returns.
 * The C caller MUST NOT free it separately.
 *
 * user_data MUST remain valid until smf_mghc_drop(*out) returns.
 * Thread-safety is the caller's responsibility.
 */
/* typedef int (*SmfLapAtTFn)(...);  -- defined in semiflow.h */

/*---------------------------------------------------------------------------*/
/* Graph constructors                                                         */
/*---------------------------------------------------------------------------*/

/**
 * Construct a path graph P_n with n_nodes nodes (unit edge weights).
 *
 * Returns: Ok (0) on success; NullPtr (5) if out is null;
 *          OutOfDomain (3) if n_nodes == 0; Panic (99) on internal error.
 *
 * Caller owns the returned handle. Free with smf_graph_drop.
 */
/* SemiflowStatus smf_graph_path(uint32_t n_nodes, SmfGraph **out);
   -- declared in semiflow.h */

/**
 * Return node count of g. Returns 0 if g is null.
 */
/* uint32_t smf_graph_n_nodes(const SmfGraph *g);
   -- declared in semiflow.h */

/**
 * Free a graph handle. Null-safe (passing NULL is a no-op).
 */
/* void smf_graph_drop(SmfGraph *g);
   -- declared in semiflow.h */

/*---------------------------------------------------------------------------*/
/* GraphSignal                                                                */
/*---------------------------------------------------------------------------*/

/**
 * Allocate a graph signal from n_nodes initial values in vals[].
 *
 * Returns: Ok (0) on success; NullPtr (5) on null arg; GridMismatch (1) if
 *          n_nodes != graph node count; NanInf (2) on non-finite input.
 *
 * Caller owns the returned handle. Free with smf_graphsig_drop.
 */
/* SemiflowStatus smf_graphsig_new(const SmfGraph *graph, const double *vals,
                                  uint32_t n_nodes, SmfGraphSig **out);
   -- declared in semiflow.h */

/**
 * Copy signal values into caller-owned buffer buf[0..buf_len].
 *
 * Returns: Ok (0); NullPtr (5) on null; GridMismatch (1) if buf_len too small.
 */
/* SemiflowStatus smf_graphsig_values(const SmfGraphSig *sig, double *buf,
                                     uint32_t buf_len);
   -- declared in semiflow.h */

/**
 * Return signal length. Returns 0 if sig is null.
 */
/* uint32_t smf_graphsig_len(const SmfGraphSig *sig);
   -- declared in semiflow.h */

/**
 * Free a graph signal handle. Null-safe.
 */
/* void smf_graphsig_drop(SmfGraphSig *sig);
   -- declared in semiflow.h */

/*---------------------------------------------------------------------------*/
/* GraphHeatChernoff (order-1 static Laplacian)                              */
/*---------------------------------------------------------------------------*/

/**
 * Construct a GraphHeatChernoff state.
 *
 * Solves ∂ₜu = −L_G u using order-1 Chernoff approximation.
 *
 * n_steps: Chernoff step count (>= 1).
 *
 * Returns: Ok (0); NullPtr (5) on null; OutOfDomain (3) if n_steps == 0.
 *
 * Caller owns the returned handle. Free with smf_ghc_drop.
 */
/* SemiflowStatus smf_ghc_new(const SmfGraph *graph, const SmfGraphSig *init_sig,
                             uint32_t n_steps, SmfGhc **out);
   -- declared in semiflow.h */

/**
 * Evolve graph-heat state by tau using n_steps Chernoff sub-steps.
 *
 * Mutates state in-place. Read current values with smf_ghc_current.
 *
 * Returns: Ok (0); NullPtr (5) if state null; OutOfDomain (3) if
 *          tau <= 0, non-finite, or n_steps == 0.
 */
/* SemiflowStatus smf_ghc_apply_into(SmfGhc *state, double tau, uint32_t n_steps);
   -- declared in semiflow.h */

/**
 * Copy current signal values into buf[0..buf_len].
 *
 * Returns: Ok (0); NullPtr (5) on null; GridMismatch (1) if buf too small.
 */
/* SemiflowStatus smf_ghc_current(const SmfGhc *state, double *buf, uint32_t buf_len);
   -- declared in semiflow.h */

/**
 * Free a SmfGhc handle. Null-safe.
 */
/* void smf_ghc_drop(SmfGhc *state);
   -- declared in semiflow.h */

/*---------------------------------------------------------------------------*/
/* MagnusGraphHeatChernoff (K=4 Magnus, time-dependent Laplacian)            */
/*---------------------------------------------------------------------------*/

/**
 * Construct a MagnusGraphHeatChernoff state.
 *
 * Solves ∂ₜu = −L_G(t) u using fourth-order Magnus + GL₄ quadrature.
 *
 * Parameters:
 *   graph                   — topology graph (borrowed; must remain valid).
 *   init_sig                — initial condition signal.
 *   lap_at_t_fn             — time-to-Laplacian callback (see SmfLapAtTFn).
 *   user_data               — passed verbatim to lap_at_t_fn; must remain
 *                             valid until smf_mghc_drop(*out) returns.
 *   rho_bar_max             — spectral-radius bound (> 0).
 *   convergence_radius_check — non-zero to enable Magnus convergence check.
 *   out                     — written on success.
 *
 * Returns: Ok (0); NullPtr (5) on null arg or null callback;
 *          OutOfDomain (3) if rho_bar_max <= 0 or non-finite.
 *
 * Caller owns the returned handle. Free with smf_mghc_drop.
 */
/* SemiflowStatus smf_mghc_new(const SmfGraph *graph, const SmfGraphSig *init_sig,
                              SmfLapAtTFn lap_at_t_fn, void *user_data,
                              double rho_bar_max, int convergence_radius_check,
                              SmfMghc **out);
   -- declared in semiflow.h */

/**
 * Evolve Magnus state by tau using n_steps sub-steps.
 *
 * Each sub-step calls lap_at_t_fn at two GL₄ quadrature points.
 * The internal time cursor advances by tau on success.
 *
 * Returns: Ok (0); NullPtr (5) if state null; OutOfDomain (3) if tau <= 0,
 *          non-finite, or n_steps == 0; ConvergenceFailed (7) on radius check
 *          failure; Panic (99) on internal error.
 */
/* SemiflowStatus smf_mghc_apply_into(SmfMghc *state, double tau, uint32_t n_steps);
   -- declared in semiflow.h */

/**
 * Copy current signal values into buf[0..buf_len].
 *
 * Returns: Ok (0); NullPtr (5) on null; GridMismatch (1) if buf too small.
 */
/* SemiflowStatus smf_mghc_current(const SmfMghc *state, double *buf, uint32_t buf_len);
   -- declared in semiflow.h */

/**
 * Free a SmfMghc handle. Null-safe.
 */
/* void smf_mghc_drop(SmfMghc *state);
   -- declared in semiflow.h */

/*---------------------------------------------------------------------------*/
/* Status code reference (from SemiflowStatus in semiflow.h)                   */
/*---------------------------------------------------------------------------*/
/*
 * SMF_OK                 = 0
 * SMF_GRID_MISMATCH      = 1
 * SMF_NAN_INF            = 2
 * SMF_OUT_OF_DOMAIN      = 3
 * SMF_NULL_PTR           = 5
 * SMF_CONVERGENCE_FAILED = 7
 * SMF_PANIC              = 99
 */

#ifdef __cplusplus
}
#endif

#endif /* SEMIFLOW_GRAPH_H */
