// SPDX-License-Identifier: MIT OR Apache-2.0
// DO NOT EDIT — generated by `cargo run -p xtask -- ffi-headers`
// C ABI for semiflow-core (experimental, v0.10.0).
// See crates/semiflow-ffi/README.md and docs/adr/0028-ffi-pyo3-wasm-v0_10.md.

#ifndef SEMIFLOW_H
#define SEMIFLOW_H

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
/**
 * Diffusion coefficient callback: `double f(double x, void *user_data)`.
 *
 * Used by `smf_state_new_with_closure` (ADR-0034).
 * The function MUST be pure and panic-free.
 * `user_data` is the opaque pointer supplied by the caller.
 */
typedef double (*SemiflowAFn)(double x, void *user_data);

/**
 * Status codes returned by all `smf_*` C functions.
 *
 * Integer values are stable ABI; do not reorder.  New variants (gap or
 * append) require a major version bump per ADR-0028.
 */
typedef enum {
  /**
   * Operation completed successfully.
   */
  Ok = 0,
  /**
   * Grid geometry mismatch (e.g. `n < 4`, `xmin >= xmax`, wrong length).
   */
  GridMismatch = 1,
  /**
   * Non-finite value (NaN or Inf) encountered in input data.
   */
  NanInf = 2,
  /**
   * Argument violates a domain precondition other than NaN/Inf or grid.
   */
  OutOfDomain = 3,
  /**
   * Grid resolution too coarse for the requested Chernoff shift.
   */
  BoundaryFailure = 4,
  /**
   * A required pointer argument was null.
   */
  NullPtr = 5,
  /**
   * CFL bound violated for the truncated-exp K=4 power series.
   */
  CflViolated = 6,
  /**
   * Iterative solver did not converge within the iteration cap.
   */
  ConvergenceFailed = 7,
  /**
   * Requested feature is not supported in this build.
   */
  Unsupported = 8,
  /**
   * A Rust panic was caught at the FFI boundary.
   *
   * This indicates an internal bug; please file an issue.
   */
  Panic = 99,
} SemiflowStatus;

typedef struct Option_RmzLapAtTFn Option_RmzLapAtTFn;

typedef struct Option_RmzWeightAtTFn Option_RmzWeightAtTFn;

/**
 * Opaque FFI handle to `AdjointFokkerPlanckChernoff<DiffusionChernoff<f64>, f64, 1>`.
 *
 * Obtained from `smf_adjoint_fp_new_brownian_1d_v3`; passed to `_step_v3` /
 * `_free_v3`. Do not dereference or allocate this struct from C.
 */
typedef struct {
  uint8_t _private[0];
} SmfAdjointFpV3;

/**
 * Opaque handle to a semiflow semigroup state.
 *
 * C callers receive a `SemiflowState *` from `smf_state_new_*` and pass it
 * to other API functions.  The struct body is zero-sized and must not be
 * dereferenced or heap-allocated by the caller; all allocation is managed by
 * the Rust runtime.  Free with `smf_state_free`.
 *
 * The actual data is a `Box<SemiflowStateInner>` whose raw pointer is cast to
 * `*mut SemiflowState` by `ffi.rs`.
 */
typedef struct {
  uint8_t _private[0];
} SemiflowState;

/**
 * Opaque handle to a `Graph<f64>`.
 *
 * C callers must not dereference this struct. Allocate with `smf_graph_path`,
 * free with `smf_graph_drop`.
 */
typedef struct {
  uint8_t _private[0];
} SmfGraph;

/**
 * Opaque handle to a `GraphSignal<f64>`.
 *
 * Allocate with `smf_graphsig_new`, free with `smf_graphsig_drop`.
 */
typedef struct {
  uint8_t _private[0];
} SmfGraphSig;

/**
 * Opaque handle to a `GraphHeatChernoff<f64>` semigroup state.
 *
 * Allocate with `smf_ghc_new`, free with `smf_ghc_drop`.
 */
typedef struct {
  uint8_t _private[0];
} SmfGhc;

/**
 * Opaque handle to a `MagnusGraphHeatChernoff<f64>` state.
 *
 * Allocate with `smf_mghc_new`, free with `smf_mghc_drop`.
 */
typedef struct {
  uint8_t _private[0];
} SmfMghc;

/**
 * Opaque handle to a `GraphHeat6thChernoff<f64>` semigroup state.
 */
typedef struct {
  uint8_t _private[0];
} SmfGhc6;

/**
 * Opaque handle to a `VarCoefMagnusGraphHeatChernoff<f64>` state.
 */
typedef struct {
  uint8_t _private[0];
} SmfVcMghc;

/**
 * Opaque handle to a hyper-dual Greeks evolver (`Dual<Dual<f64>>` field).
 *
 * C callers receive this from `smf_greeks_evolver_new_heat_1d_unit_v3`
 * and pass it to `smf_heat1d_greeks_v3` / `smf_greeks_evolver_free_v3`.
 * Do not dereference or heap-allocate this struct from C.
 */
typedef struct {
  uint8_t _private[0];
} SmfGreeksEvolverV3;

/**
 * Opaque FFI handle to a `ResolventJumpChernoff<DiffusionChernoff<f64>, f64>`.
 *
 * C callers receive this from `smf_resolvent_jump_new_heat_1d_unit_v3` and
 * pass it to `smf_resolvent_jump_apply_v3` / `smf_resolvent_jump_free_v3`.
 * Do not dereference or allocate this struct from C.
 */
typedef struct {
  uint8_t _private[0];
} SmfResolventJumpV3;

/**
 * Opaque FFI handle to a `ResolventJumpChernoff2D<f64>`.
 *
 * C callers receive this from `smf_resolvent_jump_2d_new_heat_unit_v3` and
 * pass it to `smf_resolvent_jump_2d_apply_v3` / `_free_v3`.
 * Do not dereference or allocate this struct from C.
 */
typedef struct {
  uint8_t _private[0];
} SmfResolventJump2DV3;

/**
 * Opaque FFI handle to a `ResolventJumpChernoff3D<f64>`.
 *
 * C callers receive this from `smf_resolvent_jump_3d_new_heat_unit_v3` and
 * pass it to `smf_resolvent_jump_3d_apply_v3` / `_free_v3`.
 * Do not dereference or allocate this struct from C.
 */
typedef struct {
  uint8_t _private[0];
} SmfResolventJump3DV3;

/**
 * Opaque handle to a v3.0 [`Evolver`] over `DiffusionChernoff<f64>`.
 *
 * C callers receive a `SmfEvolverV3 *` from `smf_evolver_new_heat_1d_unit_v3`
 * and pass it to other `smf_evolver_*_v3` functions.  Free with
 * `smf_evolver_free_v3`.  Do not dereference or heap-allocate this struct.
 */
typedef struct {
  uint8_t _private[0];
} SmfEvolverV3;

/**
 * C-ABI mirror of the Rust [`Growth<f64>`] struct (v3.0, ADR-0074).
 *
 * Returned by [`smf_growth_v3`] by value; no heap allocation.
 *
 * ```c
 * SmfGrowthV3 g = smf_growth_v3(ev);
 * printf("multiplier=%f omega=%f\n", g.multiplier, g.omega);
 * ```
 */
typedef struct {
  /**
   * M in `‖S(τ)‖ ≤ M · exp(ω · τ)`.  Always `≥ 1`.
   */
  double multiplier;
  /**
   * ω in `‖S(τ)‖ ≤ M · exp(ω · τ)`.  Finite.
   */
  double omega;
} SmfGrowthV3;

/**
 * Opaque handle to a `DynamicWentzellChernoff` evolver for 1D half-line heat.
 *
 * C callers receive this from `smf_wentzell_evolver_new_heat_1d_unit_v3`
 * and pass it to `smf_wentzell_evolve_v3` / `smf_wentzell_evolver_free_v3`.
 * Do not dereference or heap-allocate this struct from C.
 */
typedef struct {
  uint8_t _private[0];
} SmfWentzellEvolverV3;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Create an adjoint Fokker-Planck handle for the Brownian 1D benchmark.
 *
 * ## Parameters
 * - `a`          — diffusion coefficient (`h = 2√(aτ)`). Must be ≥ 0 and finite.
 * - `b`          — drift coefficient (`k = 2bτ`). Must be finite.
 * - `c`          — reaction coefficient (mass factor `1 + τc`). Must be finite.
 * - `max_steps`  — `DoS` cap: output buffer must hold `4^max_steps * n_in` Diracs.
 * - `out_ev`     — receives the opaque pointer on success.
 *
 * ## Return values
 * `Ok` | `NullPtr` | `OutOfDomain` | `Panic`.
 *
 * # Safety
 * - `out_ev` must be a valid writable `*mut *mut SmfAdjointFpV3`.
 */
SemiflowStatus smf_adjoint_fp_new_brownian_1d_v3(double a,
                                                double b,
                                                double c,
                                                uintptr_t max_steps,
                                                SmfAdjointFpV3 **out_ev);

/**
 * Free an adjoint FP handle. Null-safe; do not use after this call.
 *
 * # Safety
 * - `ev` must be null or a live pointer from `smf_adjoint_fp_new_brownian_1d_v3`.
 */
void smf_adjoint_fp_free_v3(SmfAdjointFpV3 *ev);

/**
 * Apply `n_steps` adjoint Fokker-Planck steps; write output Diracs into caller buffers.
 *
 * Input measure: `n_in` Diracs at `pos_in[i], w_in[i]` (both length `n_in`).
 * Output measure written into `pos_out[0..out_n_written]` and `w_out[0..out_n_written]`
 * where `out_n_written` is stored in `*out_n`.
 *
 * Output buffer capacity must be `out_cap >= 4^n_steps * n_in` Diracs.
 * If `out_cap < 4^n_steps * n_in`, returns `GridMismatch`.
 *
 * Dirac count grows ×4 per step — bound `n_steps <= max_steps` (checked at call).
 *
 * ## Preconditions
 * - `ev` non-null, from `smf_adjoint_fp_new_brownian_1d_v3`.
 * - `tau > 0`, finite.
 * - `n_steps >= 1` and `n_steps <= max_steps`.
 * - `pos_in`, `w_in` non-null, length `n_in`.
 * - `pos_out`, `w_out` non-null, length `out_cap >= 4^n_steps * n_in`.
 * - `out_n` non-null.
 *
 * # Safety
 * Raw pointer dereferences guarded by null checks and length validation.
 */
SemiflowStatus smf_adjoint_fp_step_v3(SmfAdjointFpV3 *ev,
                                     double tau,
                                     uintptr_t n_steps,
                                     const double *pos_in,
                                     const double *w_in,
                                     uintptr_t n_in,
                                     double *pos_out,
                                     double *w_out,
                                     uintptr_t out_cap,
                                     uintptr_t *out_n);

/**
 * Allocate a heat-equation state with diffusion coefficient `a(x) = 1.0`.
 *
 * Solves `∂_t u = ∂_xx u` (unit diffusion) on `[xmin, xmax]` with `n` nodes.
 * The default internal step count is 100; pass a different `n_steps` to
 * `smf_evolve` to override it per call.
 *
 * ## Preconditions
 * - `xmin < xmax`; both must be finite.
 * - `n >= 4` (minimum grid resolution for the Chernoff kernel).
 * - `u0_len == n`; the initial-condition length must match the grid.
 * - All elements of `u0[0..u0_len]` must be finite (no NaN, no Inf).
 * - `u0` is a valid pointer to at least `u0_len` contiguous `f64` values.
 * - `out_state` is a valid pointer to a `*mut SemiflowState` location.
 * - Neither `u0` nor `out_state` may be null.
 *
 * ## Postconditions
 * - On `Ok`: `*out_state` points to a freshly allocated, heap-resident
 *   `SemiflowState`.  Ownership transfers to the caller; free with
 *   `smf_state_free`.
 * - On any error: `*out_state` is left unchanged; no allocation escapes.
 *
 * ## Return values
 * - `Ok` (0) — success; `*out_state` is set.
 * - `NullPtr` (5) — `u0` or `out_state` is null.
 * - `GridMismatch` (1) — `n < 4`, `xmin >= xmax`, or `u0_len != n`.
 * - `NanInf` (2) — a `u0` element is NaN or Inf.
 * - `Panic` (99) — internal Rust panic caught at boundary (file a bug).
 *
 * ## Ownership
 * Caller owns the returned handle.  Free with `smf_state_free`.
 *
 * # Safety
 * - `u0` must be a valid pointer to `u0_len` contiguous `f64` values.
 * - `out_state` must be a valid pointer to a `*mut SemiflowState`.
 * - Returns `NullPtr` if any pointer argument is null.
 */
SemiflowStatus smf_state_new_heat_1d_unit(double xmin,
                                             double xmax,
                                             uintptr_t n,
                                             const double *u0,
                                             uintptr_t u0_len,
                                             SemiflowState **out_state);

/**
 * Allocate a heat-equation state with a variable diffusion coefficient `a(x)`.
 *
 * Solves `∂_t u = ∂_x(a(x)·∂_x u)` on `[xmin, xmax]` with `n` nodes using
 * the ζ-A Chernoff formula (ADR-0008, order-2 consistency, `a ∈ C³`).
 *
 * ## Callback contract
 *
 * - `a`, `a_prime`, `a_double_prime` are C function pointers of type
 *   `double (*)(double x, void *user_data)`.  None may be null.
 * - `user_data` is threaded through to all three callbacks unchanged.
 *   Pass `NULL` if no state is needed.
 * - Callbacks MUST be pure (no global state mutation) and panic-free.
 *   They will be invoked many times per `smf_evolve` call (once per
 *   grid node per Chernoff step — up to O(N × `n_steps`) calls total).
 * - Callbacks MUST NOT throw C++ exceptions across the boundary; that is UB.
 * - Returning NaN or Inf from a callback causes `DomainViolation` from the
 *   integrator, surfaced as `OutOfDomain` or `NanInf` from `smf_evolve`.
 *
 * ## Lifetime / thread-safety
 *
 * `user_data` MUST remain valid until `smf_state_free(*out_state)`
 * returns.  Violation is undefined behaviour.
 *
 * The Rust wrapper marks `user_data` as `Send + Sync`.  Thread-safety is the
 * **caller's** responsibility:
 * - Read-only data (e.g. `const double *params`) is always safe.
 * - Shared mutable data without external synchronisation is UB.
 *
 * ## Panic safety
 *
 * Each callback invocation is wrapped in `catch_unwind`.  On an unexpected
 * Rust panic inside the callback, the sentinel value `0.0` is returned and
 * the panic is not propagated.  The entire constructor body is also wrapped
 * in `catch_unwind`; a panic there returns `Panic` (99).
 *
 * ## Preconditions
 *
 * Same as `smf_state_new_heat_1d_unit`, plus:
 * - `a`, `a_prime`, `a_double_prime` must be non-null function pointers.
 * - `a_norm_bound > 0` (upper bound for `‖a‖∞`; used for diagnostics only).
 * - `a(x) > 0` for all `x ∈ [xmin, xmax]` (strict ellipticity).
 *
 * ## Return values
 * - `Ok` (0) — success; `*out_state` is set.
 * - `NullPtr` (5) — any pointer argument is null.
 * - `GridMismatch` (1) — `n < 4`, `xmin >= xmax`, or `u0_len != n`.
 * - `NanInf` (2) — a `u0` element is NaN or Inf.
 * - `OutOfDomain` (3) — `a(x) <= 0` or non-finite detected by integrator.
 * - `Panic` (99) — internal Rust panic caught at boundary (file a bug).
 *
 * ## Ownership
 * Caller owns the returned handle.  Free with `smf_state_free`.
 *
 * # Safety
 * - `a`, `a_prime`, `a_double_prime` must be valid, non-null C function
 *   pointers that remain callable for the lifetime of `*out_state`.
 * - `user_data` must remain valid until `smf_state_free(*out_state)`.
 * - `u0` must be a valid pointer to `u0_len` contiguous `f64` values.
 * - `out_state` must be a valid pointer to a `*mut SemiflowState`.
 */
SemiflowStatus smf_state_new_with_closure(double xmin,
                                             double xmax,
                                             uintptr_t n,
                                             double (*a)(double, void*),
                                             double (*a_prime)(double, void*),
                                             double (*a_double_prime)(double, void*),
                                             void *user_data,
                                             double a_norm_bound,
                                             const double *u0,
                                             uintptr_t u0_len,
                                             SemiflowState **out_state);

/**
 * Free a state previously allocated by `smf_state_new_*`.
 *
 * Null-safe: passing `NULL` is a no-op.
 *
 * ## Preconditions
 * - `state` is null, or a live pointer previously returned by
 *   `smf_state_new_*` that has not yet been freed.
 *
 * ## Postconditions
 * - The heap memory for the state is released.
 * - After this call `state` is dangling; do not use it again.
 *
 * ## Return values
 * This function is `void`.  Errors (including internal panics) are silently
 * discarded because there is no meaningful recovery in a destructor.
 *
 * ## Ownership
 * Takes ownership and destroys the handle.
 *
 * # Safety
 * - `state` must be either null or a pointer obtained from
 *   `smf_state_new_*` that has not already been freed.
 */
void smf_state_free(SemiflowState *state);

/**
 * Advance the state by time `t` using `n_steps` Chernoff iterations.
 *
 * Mutates the state in place.  Call `smf_state_values` afterwards to
 * copy the updated grid values.
 *
 * ## Preconditions
 * - `state` is non-null and was obtained from `smf_state_new_*`.
 * - `t >= 0.0` and finite.
 * - `n_steps >= 1`.
 *
 * ## Postconditions
 * - On `Ok`: the internal current function is replaced by the Chernoff
 *   approximation advanced by time `t` using `n_steps` iterations.
 *   The semigroup step count is updated to `n_steps` for subsequent calls.
 * - On any error: the state is left unchanged.
 *
 * ## Edge cases
 * - `t = 0.0` is **accepted** but does NOT guarantee an identity transform.
 *   Applying the kernel `n_steps` times with `tau = 0` produces numerically
 *   underflowed values rather than `u0` exactly.  Callers needing identity
 *   should skip the call instead of passing `t = 0.0`.
 * - `t < 0.0` — heat equation is ill-posed backwards.
 * - `n_steps = 0` — meaningless; treated as a precondition violation.
 * - NaN or Inf `t` — routed via internal validation.
 *
 * ## Return values
 * - `Ok` (0) — success; state updated.
 * - `NullPtr` (5) — `state` is null.
 * - `OutOfDomain` (3) — `t < 0`, `t` is NaN/Inf, or `n_steps == 0`.
 * - `CflViolated` (6) — CFL constraint violated for the chosen `t`/`n_steps`.
 * - `BoundaryFailure` (4) — grid resolution too coarse for the Chernoff shift.
 * - `ConvergenceFailed` (7) — iterative solver did not converge.
 * - `Panic` (99) — internal Rust panic caught at boundary (file a bug).
 *
 * ## Ownership
 * Borrows `state` for the duration of the call; does not transfer ownership.
 *
 * # Safety
 * - `state` must be a valid non-null pointer obtained from
 *   `smf_state_new_*`.
 */
SemiflowStatus smf_evolve(SemiflowState *state, double t, uintptr_t n_steps);

/**
 * Advance state in place using a caller-provided buffer (Wave 5, ADR-0045 §2).
 *
 * Borrows `buf` for the duration of the call only; no ownership transfer.
 * On `Ok`, `buf[0..buf_len]` contains the evolved values.  On error, `buf`
 * may be partially written (indeterminate state).
 *
 * ## Preconditions
 * - `state` is non-null and was obtained from `smf_state_new_*`.
 * - `buf` is non-null and writable for at least `buf_len` `f64` values,
 *   well-aligned for `f64`.
 * - `buf_len == smf_state_size(state)`.
 * - `buf` must not alias the state's internal buffer (UB if violated).
 * - `tau > 0` and finite; `n_steps >= 1`.
 *
 * ## Return values
 * - `Ok` (0)              — `buf` now holds the evolved values.
 * - `NullPtr` (5)         — `state` or `buf` is null.
 * - `OutOfDomain` (3)     — `tau <= 0`, non-finite, or `n_steps == 0`.
 * - `GridMismatch` (1)    — `buf_len != smf_state_size(state)`.
 * - `Panic` (99)          — internal Rust panic caught at boundary (file a bug).
 *
 * # Safety
 * - `state` must be a valid non-null pointer obtained from `smf_state_new_*`.
 * - `buf` must be valid for `buf_len` contiguous, writable, well-aligned `f64`s.
 */
SemiflowStatus smf_evolve_inplace(SemiflowState *state,
                                     double *buf,
                                     uintptr_t buf_len,
                                     double tau,
                                     uintptr_t n_steps);

/**
 * Copy current grid values into `out_buf`.
 *
 * Writes exactly `smf_state_size(state)` `f64` values starting at
 * `out_buf`.  The write is a flat memcopy; no partial writes occur on error.
 *
 * ## Preconditions
 * - `state` is non-null and was obtained from `smf_state_new_*`.
 * - `out_buf` is non-null and writable for at least `out_buf_len` `f64`
 *   values (≥ `smf_state_size(state)` elements).
 * - `out_buf_len >= smf_state_size(state)`.
 *
 * ## Postconditions
 * - On `Ok`: `out_buf[0..n]` contains the current grid values.
 * - On error: `out_buf` is left unchanged.
 *
 * ## Return values
 * - `Ok` (0) — values copied.
 * - `NullPtr` (5) — `state` or `out_buf` is null.
 * - `GridMismatch` (1) — `out_buf_len < smf_state_size(state)`.
 * - `Panic` (99) — internal Rust panic caught at boundary (file a bug).
 *
 * ## Ownership
 * Borrows `state` and writes to `out_buf`; does not transfer ownership.
 *
 * # Safety
 * - `state` must be valid and non-null.
 * - `out_buf` must be valid for `out_buf_len` `f64` writes.
 */
SemiflowStatus smf_state_values(const SemiflowState *state,
                                   double *out_buf,
                                   uintptr_t out_buf_len);

/**
 * Return the number of grid nodes (length of the value array).
 *
 * Returns `0` if `state` is null.  Always safe to call before allocating an
 * output buffer for `smf_state_values`.
 *
 * ## Preconditions
 * - `state` is null or a live pointer from `smf_state_new_*`.
 *
 * ## Postconditions
 * - Returns the grid size `n` passed to the constructor, or `0` on null.
 *
 * ## Return values
 * This function returns `usize`, not `SemiflowStatus`; it cannot fail.
 *
 * ## Ownership
 * Borrows `state` for the duration of the call; does not transfer ownership.
 *
 * # Safety
 * - `state` must be null or a valid pointer obtained from `smf_state_new_*`.
 */
uintptr_t smf_state_size(const SemiflowState *state);

/**
 * Return a static null-terminated C string describing `s`.
 *
 * The returned pointer is valid for the lifetime of the process; do not free.
 *
 * ## Preconditions
 * - `s` is any valid `SemiflowStatus` discriminant.
 *
 * ## Postconditions
 * - Returns a pointer to a static ASCII string matching the variant name
 *   (e.g. `"Ok"`, `"GridMismatch"`, `"Panic"`).
 *
 * ## Return values
 * Always returns a non-null pointer; cannot fail.
 */
const char *smf_status_str(SemiflowStatus s);

/**
 * Return the crate version string as a static null-terminated C string.
 *
 * Example: `"0.10.0"`.  The returned pointer is valid for the lifetime of
 * the process; do not free.
 *
 * ## Return values
 * Always returns a non-null pointer; cannot fail.
 */
const char *smf_version(void);

/**
 * Construct a `GraphHeatChernoff` (order-1) state from a graph + initial signal.
 *
 * Solves `∂ₜu = −L_G u` (order-1 Chernoff, Wave 2.1A).
 *
 * ## Preconditions
 * - `graph` is non-null; obtained from a `smf_graph_*` constructor.
 * - `init_sig` is non-null; obtained from `smf_graphsig_new` with the same graph.
 * - `n_steps >= 1`.
 * - `out` is a valid non-null pointer to `*mut SmfGhc`.
 *
 * ## Postconditions
 * - On `Ok`: `*out` is a freshly allocated `SmfGhc` handle. The initial
 *   condition is a copy of `init_sig`. Ownership transfers to the caller;
 *   free with `smf_ghc_drop`.
 * - On error: `*out` is left unchanged.
 *
 * ## Return values
 * - `Ok` (0)           — success.
 * - `NullPtr` (5)      — any pointer is null.
 * - `OutOfDomain` (3)  — `n_steps == 0`.
 * - `Panic` (99)       — internal Rust panic.
 *
 * ## Ownership
 * Caller owns the returned handle. Free with `smf_ghc_drop`.
 *
 * # Safety
 * - `graph` and `init_sig` must be valid non-null pointers from their constructors.
 * - `out` must be a valid pointer to `*mut SmfGhc`.
 */
SemiflowStatus smf_ghc_new(const SmfGraph *graph,
                          const SmfGraphSig *init_sig,
                          uint32_t n_steps,
                          SmfGhc **out);

/**
 * Evolve the graph-heat state by `tau` using `n_steps` Chernoff steps.
 *
 * Mutates state in place. Call `smf_ghc_current` afterwards to read values.
 *
 * ## Preconditions
 * - `state` is non-null and was obtained from `smf_ghc_new`.
 * - `tau > 0` and finite.
 * - `n_steps >= 1`.
 *
 * ## Postconditions
 * - On `Ok`: internal signal updated; `n_steps` stored for next call.
 * - On error: state is left unchanged.
 *
 * ## Return values
 * - `Ok` (0)           — success.
 * - `NullPtr` (5)      — `state` is null.
 * - `OutOfDomain` (3)  — `tau <= 0`, non-finite, or `n_steps == 0`.
 * - `Panic` (99)       — internal Rust panic.
 *
 * ## Ownership
 * Borrows `state` for the duration; does not transfer ownership.
 *
 * # Safety
 * - `state` must be a valid non-null pointer from `smf_ghc_new`.
 */
SemiflowStatus smf_ghc_apply_into(SmfGhc *state, double tau, uint32_t n_steps);

/**
 * Copy current signal values from the graph-heat state into `buf`.
 *
 * ## Preconditions
 * - `state` is non-null and was obtained from `smf_ghc_new`.
 * - `buf` is non-null and writable for at least `buf_len` `f64` values.
 * - `buf_len >= n_nodes`.
 *
 * ## Return values
 * - `Ok` (0)           — values copied.
 * - `NullPtr` (5)      — `state` or `buf` is null.
 * - `GridMismatch` (1) — `buf_len` too small.
 * - `Panic` (99)       — internal Rust panic.
 *
 * # Safety
 * - `state` must be a valid non-null pointer from `smf_ghc_new`.
 * - `buf` must be valid for `buf_len` `f64` writes.
 */
SemiflowStatus smf_ghc_current(const SmfGhc *state, double *buf, uint32_t buf_len);

/**
 * Free a `SmfGhc` handle. Null-safe.
 *
 * # Safety
 * - `state` must be null or a pointer from `smf_ghc_new` not yet freed.
 */
void smf_ghc_drop(SmfGhc *state);

/**
 * Construct a `MagnusGraphHeatChernoff` (K=4) state.
 *
 * Solves `∂ₜu = −L_G(t) u` using fourth-order Magnus + GL₄ quadrature.
 *
 * ## Callback contract (`lap_at_t_fn`)
 *
 * `lap_at_t_fn(t, user_data, out_graph)` is called with sample time `t`.
 * The C callback MUST:
 * - Allocate a new graph handle (e.g. via `smf_graph_path`) and write its
 *   pointer to `*out_graph`.
 * - Return 0 on success; non-zero on error.
 * - Preserve the topology (`row_ptr`/`col_idx`) of the base `graph`.
 * - Not throw C++ exceptions across the boundary (UB).
 *
 * The Rust side takes ownership of `*out_graph` immediately after the
 * callback returns — the C caller MUST NOT free it separately.
 *
 * `user_data` MUST remain valid until `smf_mghc_drop(*out)` returns.
 * It is stored as a `usize` cast so the closure is `Send + Sync`. Thread-
 * safety is the **caller's** responsibility.
 *
 * ## Preconditions
 * - `graph` is non-null; obtained from a `smf_graph_*` constructor.
 * - `init_sig` is non-null; obtained from `smf_graphsig_new`.
 * - `lap_at_t_fn` is non-null.
 * - `rho_bar_max > 0` and finite.
 * - `out` is non-null.
 *
 * ## Return values
 * - `Ok` (0)           — success.
 * - `NullPtr` (5)      — any pointer is null.
 * - `OutOfDomain` (3)  — `rho_bar_max <= 0` or non-finite.
 * - `Panic` (99)       — internal Rust panic.
 *
 * ## Ownership
 * Caller owns the returned handle. Free with `smf_mghc_drop`.
 *
 * # Safety
 * - `graph`, `init_sig`, and `out` must be valid non-null pointers.
 * - `lap_at_t_fn` must be a valid C function pointer for the handle's lifetime.
 * - `user_data` must remain valid until `smf_mghc_drop(*out)` returns.
 */
SemiflowStatus smf_mghc_new(const SmfGraph *graph,
                           const SmfGraphSig *init_sig,
                           Option_RmzLapAtTFn lap_at_t_fn,
                           void *user_data,
                           double rho_bar_max,
                           int32_t convergence_radius_check,
                           SmfMghc **out);

/**
 * Evolve the Magnus state by `tau` using `n_steps` Chernoff sub-steps.
 *
 * Each sub-step calls `lap_at_t_fn` at two GL₄ quadrature points within its
 * sub-interval. The internal time cursor advances by `tau` on success.
 *
 * ## Preconditions
 * - `state` is non-null and was obtained from `smf_mghc_new`.
 * - `tau > 0` and finite.
 * - `n_steps >= 1`.
 *
 * ## Postconditions
 * - On `Ok`: current signal updated; time cursor advanced by `tau`.
 * - On error: state is partially updated (best-effort).
 *
 * ## Return values
 * - `Ok` (0)               — success; time cursor advanced.
 * - `NullPtr` (5)          — `state` is null.
 * - `OutOfDomain` (3)      — `tau <= 0`, non-finite, or `n_steps == 0`.
 * - `ConvergenceFailed` (7)— Magnus convergence-radius check failed.
 * - `Panic` (99)           — internal Rust panic.
 *
 * ## Ownership
 * Borrows `state` for the duration; does not transfer ownership.
 *
 * # Safety
 * - `state` must be a valid non-null pointer from `smf_mghc_new`.
 */
SemiflowStatus smf_mghc_apply_into(SmfMghc *state, double tau, uint32_t n_steps);

/**
 * Copy current signal values from the Magnus state into `buf`.
 *
 * ## Preconditions
 * - `state` is non-null and was obtained from `smf_mghc_new`.
 * - `buf` is non-null and writable for at least `buf_len` `f64` values.
 * - `buf_len >= n_nodes`.
 *
 * ## Return values
 * - `Ok` (0)           — values copied.
 * - `NullPtr` (5)      — `state` or `buf` is null.
 * - `GridMismatch` (1) — `buf_len` too small.
 * - `Panic` (99)       — internal Rust panic.
 *
 * # Safety
 * - `state` must be a valid non-null pointer from `smf_mghc_new`.
 * - `buf` must be valid for `buf_len` `f64` writes.
 */
SemiflowStatus smf_mghc_current(const SmfMghc *state, double *buf, uint32_t buf_len);

/**
 * Free a `SmfMghc` handle. Null-safe.
 *
 * # Safety
 * - `state` must be null or a pointer from `smf_mghc_new` not yet freed.
 */
void smf_mghc_drop(SmfMghc *state);

/**
 * Construct a path graph `P_n` with `n_nodes` nodes and unit edge weights.
 *
 * ## Preconditions
 * - `n_nodes >= 1`.
 * - `out` is a valid non-null pointer to a `*mut SmfGraph` location.
 *
 * ## Postconditions
 * - On `Ok`: `*out` points to a freshly allocated graph handle.
 *   Ownership transfers to the caller; free with `smf_graph_drop`.
 * - On error: `*out` is left unchanged.
 *
 * ## Return values
 * - `Ok` (0)           — success; `*out` is set.
 * - `NullPtr` (5)      — `out` is null.
 * - `OutOfDomain` (3)  — `n_nodes == 0`.
 * - `Panic` (99)       — internal Rust panic caught at boundary.
 *
 * ## Ownership
 * Caller owns the returned handle. Free with `smf_graph_drop`.
 *
 * # Safety
 * - `out` must be a valid pointer to a `*mut SmfGraph` location.
 */
SemiflowStatus smf_graph_path(uint32_t n_nodes, SmfGraph **out);

/**
 * Return the number of nodes in `g`.
 *
 * Returns `0` if `g` is null.
 *
 * ## Preconditions
 * - `g` is null or a live pointer from a `smf_graph_*` constructor.
 *
 * ## Return values
 * `u32` node count, or `0` on null. Cannot fail.
 *
 * ## Ownership
 * Borrows `g`; does not transfer ownership.
 *
 * # Safety
 * - `g` must be null or a valid pointer from `smf_graph_path`.
 */
uint32_t smf_graph_n_nodes(const SmfGraph *g);

/**
 * Free a graph handle previously allocated by `smf_graph_path`.
 *
 * Null-safe: passing `NULL` is a no-op.
 *
 * ## Postconditions
 * - Heap memory released. After this call `g` is dangling.
 *
 * ## Ownership
 * Takes ownership and destroys the handle.
 *
 * # Safety
 * - `g` must be null or a pointer from `smf_graph_path` not yet freed.
 */
void smf_graph_drop(SmfGraph *g);

/**
 * Allocate a graph signal of `n_nodes` nodes initialised from `vals`.
 *
 * ## Preconditions
 * - `graph` is non-null and was obtained from a `smf_graph_*` constructor.
 * - `vals` is a valid pointer to exactly `n_nodes` contiguous `f64` values.
 * - `n_nodes` equals `smf_graph_n_nodes(graph)`.
 * - `out` is a valid non-null pointer to `*mut SmfGraphSig`.
 * - All elements of `vals[0..n_nodes]` must be finite.
 *
 * ## Return values
 * - `Ok` (0)           — success; `*out` is set.
 * - `NullPtr` (5)      — any pointer argument is null.
 * - `GridMismatch` (1) — `n_nodes != smf_graph_n_nodes(graph)`.
 * - `NanInf` (2)       — a `vals` element is NaN or Inf.
 * - `Panic` (99)       — internal Rust panic.
 *
 * ## Ownership
 * Caller owns the returned handle. Free with `smf_graphsig_drop`.
 *
 * # Safety
 * - `graph` must be a valid non-null pointer from a `smf_graph_*` constructor.
 * - `vals` must be valid for `n_nodes` contiguous `f64` reads.
 * - `out` must be a valid pointer to `*mut SmfGraphSig`.
 */
SemiflowStatus smf_graphsig_new(const SmfGraph *graph,
                               const double *vals,
                               uint32_t n_nodes,
                               SmfGraphSig **out);

/**
 * Copy signal values into a caller-owned buffer.
 *
 * ## Preconditions
 * - `sig` is non-null and was obtained from `smf_graphsig_new`.
 * - `buf` is non-null and writable for at least `buf_len` `f64` values.
 * - `buf_len >= signal length`.
 *
 * ## Return values
 * - `Ok` (0)           — values copied.
 * - `NullPtr` (5)      — `sig` or `buf` is null.
 * - `GridMismatch` (1) — `buf_len < signal length`.
 * - `Panic` (99)       — internal Rust panic.
 *
 * ## Ownership
 * Borrows `sig`; does not transfer ownership.
 *
 * # Safety
 * - `sig` must be a valid non-null pointer from `smf_graphsig_new`.
 * - `buf` must be valid for `buf_len` `f64` writes.
 */
SemiflowStatus smf_graphsig_values(const SmfGraphSig *sig, double *buf, uint32_t buf_len);

/**
 * Return the number of nodes (signal length). Returns 0 if null.
 *
 * ## Ownership
 * Borrows `sig`; does not transfer ownership.
 *
 * # Safety
 * - `sig` must be null or a valid pointer from `smf_graphsig_new`.
 */
uint32_t smf_graphsig_len(const SmfGraphSig *sig);

/**
 * Free a graph signal handle. Null-safe.
 *
 * # Safety
 * - `sig` must be null or a pointer from `smf_graphsig_new` not yet freed.
 */
void smf_graphsig_drop(SmfGraphSig *sig);

/**
 * Construct a `GraphHeat6thChernoff<f64>` state from a graph and initial signal.
 *
 * ## Preconditions
 * - `graph`, `init_sig`, `out` non-null.
 * - `n_steps >= 1`.
 *
 * ## Return values
 * - `Ok` (0) — `*out` is set.
 * - `NullPtr` (5) — any pointer is null.
 * - `OutOfDomain` (3) — `n_steps == 0`.
 * - `Panic` (99) — internal panic.
 *
 * ## Ownership
 * Caller owns `*out`; free with `smf_ghc6_drop`.
 *
 * # Safety
 * All pointers must come from this crate's constructors and be valid.
 */
SemiflowStatus smf_ghc6_new(const SmfGraph *graph,
                           const SmfGraphSig *init_sig,
                           uint32_t n_steps,
                           SmfGhc6 **out);

/**
 * Advance the `GraphHeat6` semigroup by `tau` using `n_steps` Chernoff steps.
 *
 * ## Return values
 * `Ok` (0), `NullPtr` (5), `OutOfDomain` (3), `Panic` (99).
 *
 * # Safety
 * `state` must be a valid non-null pointer from `smf_ghc6_new`.
 */
SemiflowStatus smf_ghc6_apply_into(SmfGhc6 *state, double tau, uint32_t n_steps);

/**
 * Copy current `GraphHeat6` signal values into `buf`.
 *
 * # Safety
 * `state` must be a valid non-null pointer from `smf_ghc6_new`. `buf` must
 * be valid for `buf_len` `f64` writes.
 */
SemiflowStatus smf_ghc6_current(const SmfGhc6 *state, double *buf, uint32_t buf_len);

/**
 * Free a `SmfGhc6` handle. Null-safe.
 *
 * # Safety
 * `state` must be null or a pointer from `smf_ghc6_new` not yet freed.
 */
void smf_ghc6_drop(SmfGhc6 *state);

/**
 * Construct a `VarCoefMagnusGraphHeatChernoff<f64>` state.
 *
 * Wraps two C callbacks: `lap_at_t_fn` (time → Laplacian) and `a_at_t_fn`
 * (time → length-N node-weight vector). Both are called repeatedly during
 * every `apply_into` step at the GL₂ quadrature points.
 *
 * ## Preconditions
 * - `init_sig`, `out` non-null.
 * - `lap_at_t_fn`, `a_at_t_fn` non-null.
 * - `rho_bar_max > 0`, `a_sup_max > 0`, both finite.
 * - `n_nodes >= 1`.
 *
 * ## Return values
 * - `Ok` (0), `NullPtr` (5), `OutOfDomain` (3), `Panic` (99).
 *
 * # Safety
 * `init_sig` must be from `smf_graphsig_new`. `user_data_lap` and
 * `user_data_a` must remain valid until `smf_vc_mghc_drop(*out)` returns.
 */
SemiflowStatus smf_vc_mghc_new(uint32_t n_nodes,
                              const SmfGraphSig *init_sig,
                              Option_RmzLapAtTFn lap_at_t_fn,
                              void *user_data_lap,
                              Option_RmzWeightAtTFn a_at_t_fn,
                              void *user_data_a,
                              double rho_bar_max,
                              double a_sup_max,
                              int32_t convergence_radius_check,
                              SmfVcMghc **out);

/**
 * Advance the `VarCoef` Magnus state by `tau` using `n_steps` Magnus steps.
 *
 * Each sub-step samples `lap_at_t_fn` and `a_at_t_fn` at two GL₂ points
 * within its sub-interval. Time cursor advances by `tau` on success.
 *
 * # Safety
 * `state` must be from `smf_vc_mghc_new`.
 */
SemiflowStatus smf_vc_mghc_apply_into(SmfVcMghc *state, double tau, uint32_t n_steps);

/**
 * Copy current signal values from the `VarCoef` Magnus state into `buf`.
 *
 * # Safety
 * `state` must be from `smf_vc_mghc_new`; `buf` must be valid for
 * `buf_len` `f64` writes.
 */
SemiflowStatus smf_vc_mghc_current(const SmfVcMghc *state, double *buf, uint32_t buf_len);

/**
 * Free a `SmfVcMghc` handle. Null-safe.
 *
 * # Safety
 * `state` must be null or a pointer from `smf_vc_mghc_new` not yet freed.
 */
void smf_vc_mghc_drop(SmfVcMghc *state);

/**
 * Create a hyper-dual Greeks evolver for unit-diffusion heat.
 *
 * Solves `∂_t u = θ · ∂_xx u` on `[xmin, xmax]` with `n_grid` nodes.
 * `scale_theta` (θ) is seeded for Dual-AD so a single sweep yields
 * value, Δ = ∂u/∂θ, and Γ = ∂²u/∂θ² simultaneously.
 *
 * On success `*out_ev` is set.  On any error `*out_ev` is unchanged.
 *
 * ## Preconditions
 * - `xmin < xmax`, both finite.
 * - `n_grid >= 4`.
 * - `n_chernoff >= 1`.
 * - `scale_theta` finite and `> 0`.
 * - `u0` non-null; `u0_len == n_grid`; all elements finite.
 * - `out_ev` non-null.
 *
 * ## Return values
 * `Ok` | `NullPtr` | `GridMismatch` | `NanInf` | `OutOfDomain` | `Panic`.
 *
 * # Safety
 * - `u0` must point to `u0_len` readable contiguous `f64` values.
 * - `out_ev` must be a valid writable `*mut *mut SmfGreeksEvolverV3`.
 */
SemiflowStatus smf_greeks_evolver_new_heat_1d_unit_v3(double xmin,
                                                     double xmax,
                                                     uintptr_t n_grid,
                                                     uintptr_t n_chernoff,
                                                     double scale_theta,
                                                     const double *u0,
                                                     uintptr_t u0_len,
                                                     SmfGreeksEvolverV3 **out_ev);

/**
 * Free a Greeks evolver handle.  Null-safe; after the call the pointer is
 * dangling — do not use it again.
 *
 * # Safety
 * - `ev` must be null or a live pointer from `smf_greeks_evolver_new_*_v3`.
 */
void smf_greeks_evolver_free_v3(SmfGreeksEvolverV3 *ev);

/**
 * Advance by `t` and write value, Δ, and Γ to three caller-owned buffers.
 *
 * Runs `n_chernoff` hyper-dual Chernoff steps and demultiplexes the lanes:
 *   `value[i] = result[i].value.value`
 *   `delta[i] = result[i].tangent.value`
 *   `gamma[i] = result[i].tangent.tangent`
 *
 * All three output pointers must be non-null and each length `len`.
 * `len` must equal `n_grid` (the size passed to the constructor).
 *
 * ## Preconditions
 * - `ev` non-null, from `smf_greeks_evolver_new_*_v3`.
 * - `t >= 0`, finite.
 * - `out_value`, `out_delta`, `out_gamma` non-null, each length `len`.
 * - `len == n_grid`.
 *
 * ## Return values
 * `Ok` | `NullPtr` | `GridMismatch` | `OutOfDomain` | `Panic`.
 *
 * # Safety
 * - `ev` must be a live Greeks evolver handle.
 * - All three `out_*` must be valid for `len` writable `f64`s.
 */
SemiflowStatus smf_heat1d_greeks_v3(SmfGreeksEvolverV3 *ev,
                                   double t,
                                   double *out_value,
                                   double *out_delta,
                                   double *out_gamma,
                                   uintptr_t len);

/**
 * Create a resolvent-jump handle for the unit-diffusion heat kernel.
 *
 * Constructs `ResolventJumpChernoff<DiffusionChernoff<f64>>` with unit `a=1`,
 * `m_nodes` TWS contour nodes, on `[xmin, xmax]` with `n_grid` grid points.
 *
 * On success `*out_ev` is set to a non-null opaque pointer.
 *
 * ## Preconditions
 * - `xmin < xmax`, both finite.
 * - `n_grid >= 4`.
 * - `m_nodes >= 6` (geometric-regime floor, §47.4 NORMATIVE).
 * - `out_ev` non-null.
 *
 * ## Return values
 * `Ok` | `NullPtr` | `GridMismatch` | `OutOfDomain` | `Panic`.
 *
 * # Safety
 * - `out_ev` must be a valid writable `*mut *mut SmfResolventJumpV3`.
 */
SemiflowStatus smf_resolvent_jump_new_heat_1d_unit_v3(double xmin,
                                                     double xmax,
                                                     uintptr_t n_grid,
                                                     uintptr_t m_nodes,
                                                     SmfResolventJumpV3 **out_ev);

/**
 * Free a resolvent-jump handle.  Null-safe; do not use after this call.
 *
 * # Safety
 * - `ev` must be null or a live pointer from `smf_resolvent_jump_new_*_v3`.
 */
void smf_resolvent_jump_free_v3(SmfResolventJumpV3 *ev);

/**
 * Evaluate `e^{tA}g` via the TWS contour quadrature; write into `out`.
 *
 * `g` and `out` are both length `n_grid` (the value passed to the constructor).
 * The contour arithmetic (`Complex<f64>`) stays sealed inside core — only the
 * real part is returned (ABI-safety invariant, ADR-0138).
 *
 * ## Preconditions
 * - `ev` non-null, from `smf_resolvent_jump_new_*_v3`.
 * - `t > 0`, finite.
 * - `g` non-null, length `g_len == n_grid`.
 * - `out` non-null, length `out_len == n_grid`.
 *
 * ## Return values
 * `Ok` | `NullPtr` | `GridMismatch` | `OutOfDomain` | `Panic`.
 *
 * # Safety
 * - `g` must point to `g_len` readable contiguous `f64` values.
 * - `out` must point to `out_len` writable contiguous `f64` values.
 */
SemiflowStatus smf_resolvent_jump_apply_v3(SmfResolventJumpV3 *ev,
                                          double t,
                                          const double *g,
                                          uintptr_t g_len,
                                          double *out,
                                          uintptr_t out_len);

/**
 * Construct a 2D resolvent-jump handle over `[xmin,xmax]×[ymin,ymax]`.
 *
 * Grid is `nx × ny` nodes (axis-0-fastest: `idx(i,j) = j·nx + i`).
 * `m_nodes >= 6` (TWS contour floor, §47.8 NORMATIVE).
 *
 * ## Preconditions
 * - `xmin < xmax`, `ymin < ymax`, both finite.
 * - `nx >= 4`, `ny >= 4`.
 * - `m_nodes >= 6`.
 * - `out_ev` non-null.
 *
 * ## Return values
 * `Ok` | `NullPtr` | `GridMismatch` | `OutOfDomain` | `Panic`.
 *
 * # Safety
 * `out_ev` must be a valid writable `*mut *mut SmfResolventJump2DV3`.
 */
SemiflowStatus smf_resolvent_jump_2d_new_heat_unit_v3(double xmin,
                                                     double xmax,
                                                     uintptr_t nx,
                                                     double ymin,
                                                     double ymax,
                                                     uintptr_t ny,
                                                     uintptr_t m_nodes,
                                                     SmfResolventJump2DV3 **out_ev);

/**
 * Free a 2D resolvent-jump handle.  Null-safe; do not use after this call.
 *
 * # Safety
 * `ev` must be null or a live pointer from `smf_resolvent_jump_2d_new_*_v3`.
 */
void smf_resolvent_jump_2d_free_v3(SmfResolventJump2DV3 *ev);

/**
 * Evaluate `e^{tA}g` for the 2D unit-diffusion heat kernel; write into `out`.
 *
 * `g` and `out` are flat **axis-0-fastest** `f64` buffers of length `nx·ny`.
 * The complex contour arithmetic stays sealed inside core (ADR-0138).
 *
 * ## Preconditions
 * - `ev` non-null, from `smf_resolvent_jump_2d_new_*_v3`.
 * - `t > 0`, finite.
 * - `g` non-null, `g_len == nx·ny`.
 * - `out` non-null, `out_len == nx·ny`.
 *
 * ## Return values
 * `Ok` | `NullPtr` | `GridMismatch` | `OutOfDomain` | `Panic`.
 *
 * # Safety
 * - `g` must point to `g_len` readable contiguous `f64` values.
 * - `out` must point to `out_len` writable contiguous `f64` values.
 */
SemiflowStatus smf_resolvent_jump_2d_apply_v3(SmfResolventJump2DV3 *ev,
                                             double t,
                                             const double *g,
                                             uintptr_t g_len,
                                             double *out,
                                             uintptr_t out_len);

/**
 * Construct a 3D resolvent-jump handle over `[xmin,xmax]×[ymin,ymax]×[zmin,zmax]`.
 *
 * Grid is `nx × ny × nz` nodes (axis-0-fastest: `idx(i,j,k) = k·nx·ny + j·nx + i`).
 * `m_nodes >= 6` (TWS contour floor, §47.8 NORMATIVE).
 *
 * ## Preconditions
 * - All bounds finite; `xmin < xmax`, `ymin < ymax`, `zmin < zmax`.
 * - `nx,ny,nz >= 4`; `m_nodes >= 6`; `out_ev` non-null.
 *
 * ## Return values
 * `Ok` | `NullPtr` | `GridMismatch` | `OutOfDomain` | `Panic`.
 *
 * # Safety
 * `out_ev` must be a valid writable `*mut *mut SmfResolventJump3DV3`.
 */
SemiflowStatus smf_resolvent_jump_3d_new_heat_unit_v3(double xmin,
                                                     double xmax,
                                                     uintptr_t nx,
                                                     double ymin,
                                                     double ymax,
                                                     uintptr_t ny,
                                                     double zmin,
                                                     double zmax,
                                                     uintptr_t nz,
                                                     uintptr_t m_nodes,
                                                     SmfResolventJump3DV3 **out_ev);

/**
 * Free a 3D resolvent-jump handle.  Null-safe; do not use after this call.
 *
 * # Safety
 * `ev` must be null or a live pointer from `smf_resolvent_jump_3d_new_*_v3`.
 */
void smf_resolvent_jump_3d_free_v3(SmfResolventJump3DV3 *ev);

/**
 * Evaluate `e^{tA}g` for the 3D unit-diffusion heat kernel; write into `out`.
 *
 * `g` and `out` are flat **axis-0-fastest** `f64` buffers of length `nx·ny·nz`.
 * Layout: `idx(i,j,k) = k·nx·ny + j·nx + i`.  The complex contour arithmetic
 * stays sealed inside core (ADR-0138).
 *
 * ## Preconditions
 * - `ev` non-null, from `smf_resolvent_jump_3d_new_*_v3`.
 * - `t > 0`, finite.
 * - `g` non-null, `g_len == nx·ny·nz`.
 * - `out` non-null, `out_len == nx·ny·nz`.
 *
 * ## Return values
 * `Ok` | `NullPtr` | `GridMismatch` | `OutOfDomain` | `Panic`.
 *
 * # Safety
 * - `g` must point to `g_len` readable contiguous `f64` values.
 * - `out` must point to `out_len` writable contiguous `f64` values.
 */
SemiflowStatus smf_resolvent_jump_3d_apply_v3(SmfResolventJump3DV3 *ev,
                                             double t,
                                             const double *g,
                                             uintptr_t g_len,
                                             double *out,
                                             uintptr_t out_len);

/**
 * Create a v3.0 [`Evolver`] for the unit-diffusion heat equation.
 *
 * Solves `∂_t u = ∂_xx u` on `[xmin, xmax]` with `n_grid` nodes and
 * `n_chernoff` Chernoff iterations per call to `smf_evolver_evolve_into_v3`.
 *
 * On success, `*out_ev` is set to a freshly allocated handle.
 * On any error, `*out_ev` is left unchanged.
 *
 * ## Preconditions
 * - `xmin < xmax`; both finite.
 * - `n_grid >= 4`.
 * - `n_chernoff >= 1`.
 * - `u0` is non-null; `u0_len == n_grid`.
 * - All elements of `u0[0..u0_len]` must be finite.
 * - `out_ev` is a valid `*mut *mut SmfEvolverV3` (non-null).
 *
 * ## Return values
 * - `Ok` (0) — success; `*out_ev` is set.
 * - `NullPtr` (5) — `u0` or `out_ev` is null.
 * - `GridMismatch` (1) — grid geometry invalid.
 * - `NanInf` (2) — non-finite element in `u0`.
 * - `OutOfDomain` (3) — `n_chernoff == 0`.
 * - `Panic` (99) — internal panic caught at FFI boundary.
 *
 * # Safety
 * - `u0` must point to `u0_len` contiguous, readable `f64` values.
 * - `out_ev` must be a valid, writable `*mut *mut SmfEvolverV3`.
 */
SemiflowStatus smf_evolver_new_heat_1d_unit_v3(double xmin,
                                              double xmax,
                                              uintptr_t n_grid,
                                              uintptr_t n_chernoff,
                                              const double *u0,
                                              uintptr_t u0_len,
                                              SmfEvolverV3 **out_ev);

/**
 * Free an evolver handle created by `smf_evolver_new_*_v3`.
 *
 * Null-safe: passing `NULL` is a no-op.  After this call the pointer is
 * dangling; do not use it again.
 *
 * # Safety
 * - `ev` must be null or a live pointer from `smf_evolver_new_*_v3`.
 */
void smf_evolver_free_v3(SmfEvolverV3 *ev);

/**
 * Evolve the state by time `t` using the configured Chernoff iterations.
 *
 * Writes `n_grid` evolved values into `dst_buf[0..dst_len]`.
 * The internal current state is updated.  Call again to chain time steps.
 *
 * ## Preconditions
 * - `ev` is non-null and was obtained from `smf_evolver_new_*_v3`.
 * - `t >= 0.0` and finite.
 * - `dst_buf` is non-null and writable for `dst_len` `f64` values.
 * - `dst_len == n_grid` (the grid size passed to the constructor).
 *
 * ## Return values
 * - `Ok` (0) — evolved values written to `dst_buf`.
 * - `NullPtr` (5) — `ev` or `dst_buf` is null.
 * - `GridMismatch` (1) — `dst_len != n_grid`.
 * - `OutOfDomain` (3) — `t < 0`, NaN, or Inf.
 * - `Panic` (99) — internal panic at FFI boundary.
 *
 * # Safety
 * - `ev` must be a live pointer from `smf_evolver_new_*_v3`.
 * - `dst_buf` must be valid for `dst_len` writable, well-aligned `f64`s.
 */
SemiflowStatus smf_evolver_evolve_into_v3(SmfEvolverV3 *ev,
                                         double t,
                                         double *dst_buf,
                                         uintptr_t dst_len);

/**
 * Copy the current grid values into `out_buf`.
 *
 * Writes exactly `n_grid` `f64` values.  Must be called after construction
 * or `smf_evolver_evolve_into_v3` to read the current state.
 *
 * ## Return values
 * - `Ok` (0) — values written.
 * - `NullPtr` (5) — `ev` or `out_buf` is null.
 * - `GridMismatch` (1) — `out_len < n_grid`.
 * - `Panic` (99) — internal panic at FFI boundary.
 *
 * # Safety
 * - `ev` must be a live pointer from `smf_evolver_new_*_v3`.
 * - `out_buf` must be valid for `out_len` writable `f64`s.
 */
SemiflowStatus smf_evolver_values_v3(const SmfEvolverV3 *ev, double *out_buf, uintptr_t out_len);

/**
 * Return the grid size for an evolver handle.
 *
 * Returns `0` if `ev` is null.
 *
 * # Safety
 * - `ev` must be null or a live pointer from `smf_evolver_new_*_v3`.
 */
uintptr_t smf_evolver_size_v3(const SmfEvolverV3 *ev);

/**
 * Return the growth bound of the underlying [`DiffusionChernoff`] kernel.
 *
 * Returns `SmfGrowthV3 { multiplier: 0.0, omega: 0.0 }` if `ev` is null.
 *
 * For unit-diffusion, expected values: `multiplier = 1.0`, `omega = 0.0`
 * (contractive semigroup).
 *
 * # Safety
 * - `ev` must be null or a live pointer from `smf_evolver_new_*_v3`.
 */
SmfGrowthV3 smf_growth_v3(const SmfEvolverV3 *ev);

/**
 * Construct a Wentzell evolver for 1D unit-diffusion heat on a half-line.
 *
 * Constructs `DynamicWentzellChernoff` for the equation
 * `∂_t u = ∂_xx u` on `[xmin, xmax]` (half-line, boundary at `xmin`),
 * with Wentzell/Robin BC `∂_t u + γ(t)·∂_ν u + c·u = 0` at `xmin`.
 * `c_reaction ≥ 0` (boundary reaction); `n_steps` Chernoff steps per `evolve`.
 *
 * `gamma_schedule`: caller-owned `f64` buffer, length `n_steps`.
 * Host pre-samples γ at `t_k = t_offset + k·τ` (left endpoint) BEFORE calling.
 * `gamma_schedule[k] ≥ 0` and finite; length must equal `n_steps`.
 *
 * On success `*out_ev` is set to a non-null opaque pointer.
 *
 * ## Return values
 * `Ok` | `NullPtr` | `GridMismatch` | `NanInf` | `OutOfDomain` | `Panic`.
 *
 * # Safety
 * - `gamma_schedule` must point to `gamma_len` readable contiguous `f64` values.
 * - `u0` must point to `u0_len` readable contiguous `f64` values.
 * - `out_ev` must be a valid writable `*mut *mut SmfWentzellEvolverV3`.
 */
SemiflowStatus smf_wentzell_evolver_new_heat_1d_unit_v3(double xmin,
                                                       double xmax,
                                                       uintptr_t n_grid,
                                                       uintptr_t n_steps,
                                                       double c_reaction,
                                                       const double *gamma_schedule,
                                                       uintptr_t gamma_len,
                                                       const double *u0,
                                                       uintptr_t u0_len,
                                                       SmfWentzellEvolverV3 **out_ev);

/**
 * Advance the evolver by time `t` and write the evolved grid to `out`.
 *
 * Sweeps the γ-schedule once (`n_steps` Chernoff steps), sampling
 * `gamma_schedule[k]` at step `k` (left-endpoint freeze: `t_k = t_offset + k·τ`).
 * The internal current state is updated in-place (chainable).
 *
 * `out_len` must equal `n_grid` (the size passed to the constructor).
 *
 * ## Return values
 * `Ok` | `NullPtr` | `GridMismatch` | `OutOfDomain` | `Panic`.
 *
 * # Safety
 * - `ev` must be a live pointer from `smf_wentzell_evolver_new_*_v3`.
 * - `out` must be valid for `out_len` writable `f64`s.
 */
SemiflowStatus smf_wentzell_evolve_v3(SmfWentzellEvolverV3 *ev,
                                     double t,
                                     double t_offset,
                                     double *out,
                                     uintptr_t out_len);

/**
 * Free a Wentzell evolver handle.  Null-safe; do not use after this call.
 *
 * # Safety
 * - `ev` must be null or a live pointer from `smf_wentzell_evolver_new_*_v3`.
 */
void smf_wentzell_evolver_free_v3(SmfWentzellEvolverV3 *ev);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* SEMIFLOW_H */
