// AUTO-GENERATED by scripts/generate_chebyshev_nodes.py -- DO NOT EDIT
// Nodes: cos(k*pi/M); Weights: (-1)^k * delta_k (Berrut-Trefethen 2004)
//
// Split into three sibling files to comply with the ≤500-line file budget:
//   cheb_nodes_n64_128_data.rs  — M=64, M=128
//   cheb_nodes_n256_data.rs     — M=256
//   cheb_nodes_n512_data.rs     — M=512
//
// Re-generate all four files via: python3 scripts/generate_chebyshev_nodes.py
include!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/src/cheb_nodes_n64_128_data.rs"
));
include!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/src/cheb_nodes_n256_data.rs"
));
include!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/src/cheb_nodes_n512_data.rs"
));
