#!/usr/bin/env python3
"""Generate Chebyshev-Lobatto node and weight tables for grid_chebyshev_nodes.rs.

Usage: python3 scripts/generate_chebyshev_nodes.py

Outputs Rust const arrays to stdout. Redirect to regenerate the module:
    python3 scripts/generate_chebyshev_nodes.py > /tmp/cheb_tables.txt

Algorithm:
  Nodes:   x_k = cos(k * pi / M), k = 0..M  (Chebyshev-Lobatto points on [-1, 1])
  Weights: w_k = (-1)^k * delta_k,  delta_0 = delta_M = 0.5, delta_k = 1.0 else

References:
  Berrut & Trefethen 2004, SIAM Review 46:501 (formula 5.1)
  Trefethen 2000 Spectral Methods in MATLAB (Appendix)
"""

import math

M_VALUES = [8, 16, 32, 64, 128, 256, 512]

def gen_nodes(m: int) -> list[float]:
    return [math.cos(k * math.pi / m) for k in range(m + 1)]

def gen_weights(m: int) -> list[float]:
    weights = []
    for k in range(m + 1):
        delta = 0.5 if (k == 0 or k == m) else 1.0
        sign = 1.0 if k % 2 == 0 else -1.0
        weights.append(sign * delta)
    return weights

def fmt_f64(x: float) -> str:
    # Print with enough digits to round-trip f64 exactly.
    return f"{x:.20e}_f64"

def main() -> None:
    print("// AUTO-GENERATED by scripts/generate_chebyshev_nodes.py — DO NOT EDIT MANUALLY")
    print("// Re-generate: python3 scripts/generate_chebyshev_nodes.py")
    print("// Nodes: cos(k*pi/M) for k=0..M (Chebyshev-Lobatto on [-1, 1])")
    print("// Weights: (-1)^k * delta_k, delta_0=delta_M=0.5, delta_k=1.0 else (Berrut-Trefethen 2004)")
    print()
    for m in M_VALUES:
        nodes = gen_nodes(m)
        weights = gen_weights(m)
        count = m + 1
        print(f"pub(crate) const CHEB_NODES_{m}: [f64; {count}] = [")
        for x in nodes:
            print(f"    {fmt_f64(x)},")
        print("];")
        print()
        print(f"pub(crate) const CHEB_WEIGHTS_{m}: [f64; {count}] = [")
        for w in weights:
            print(f"    {fmt_f64(w)},")
        print("];")
        print()

if __name__ == "__main__":
    main()
