//! `readme` / `readme-examples-js` subcommands — one source for every published README.
//!
//! `docs/readme/README.src.md` (plus the fragments next to it) is the only place
//! the READMEs are written. `cargo xtask readme` renders it once per channel:
//!
//! | Channel  | Output                           | Published on              |
//! |----------|----------------------------------|---------------------------|
//! | `github` | `README.md`                      | GitHub front page         |
//! | `rust`   | `crates/semiflow/README.md`      | crates.io, docs.rs        |
//! | `pypi`   | `crates/semiflow-py/README.md`   | PyPI (`semiflow-pde`)     |
//! | `npm`    | `crates/semiflow-wasm/README.md` | npm (`@semiflow/wasm`)    |
//!
//! Facts that would otherwise drift are computed, not typed: the version and MSRV
//! (workspace `Cargo.toml`), the runtime dependencies and feature flags
//! (`crates/semiflow/Cargo.toml`), the Python classes and functions (`#[pyclass]`
//! registrations, `__init__.pyi`) and the WASM class tables (`#[wasm_bindgen]`
//! structs, split lite/full by the `full` feature gate in `semiflow-wasm/src/lib.rs`).
//!
//! `cargo xtask readme --check` fails when a generated file differs from what the
//! source renders to (CI runs it). `cargo xtask readme-examples-js <package-dir>`
//! runs the Node.js examples of the npm README against a built package.

use std::{
    collections::BTreeSet,
    fs,
    path::{Path, PathBuf},
    process,
};

use anyhow::{bail, Context, Result};

const SRC_DIR: &str = "docs/readme";
const TEMPLATE: &str = "README.src.md";
const REPO_BLOB: &str = "https://github.com/VolkovIlia/semiflow/blob/master/";
const GENERATED_HEADER: &str = "<!-- Generated by `cargo xtask readme` from \
docs/readme/README.src.md. Do not edit by hand: edit the source and regenerate. -->\n";

/// `(channel, output path relative to the workspace root)`.
const CHANNELS: [(&str, &str); 4] = [
    ("github", "README.md"),
    ("rust", "crates/semiflow/README.md"),
    ("pypi", "crates/semiflow-py/README.md"),
    ("npm", "crates/semiflow-wasm/README.md"),
];

/// Render (or with `--check`, verify) every channel README.
pub fn run(args: &[String]) -> Result<()> {
    let root = crate::workspace_root()?;
    let check = args.iter().any(|a| a == "--check");
    let facts = collect_facts(&root)?;
    let template = expand_includes(&root, &read(&root.join(SRC_DIR).join(TEMPLATE))?, 0)?;

    let mut stale = Vec::new();
    for (channel, out) in CHANNELS {
        let text = render(&template, channel, &facts)?;
        let path = root.join(out);
        if check {
            if fs::read_to_string(&path).ok().as_deref() != Some(text.as_str()) {
                stale.push(out);
            }
        } else {
            fs::write(&path, &text).with_context(|| format!("writing {out}"))?;
            println!("readme: wrote {out} ({channel})");
        }
    }
    if !stale.is_empty() {
        bail!(
            "readme: generated README(s) out of date: {}\n\
             Edit docs/readme/ (not the generated files) and run `cargo xtask readme`.",
            stale.join(", ")
        );
    }
    if check {
        println!(
            "readme: PASS — all {} READMEs match docs/readme/",
            CHANNELS.len()
        );
    }
    Ok(())
}

// ---------------------------------------------------------------------------
// Rendering
// ---------------------------------------------------------------------------

fn read(path: &Path) -> Result<String> {
    fs::read_to_string(path).with_context(|| format!("reading {}", path.display()))
}

/// Splice `<!-- include: file.md -->` lines (fragments may include fragments).
fn expand_includes(root: &Path, src: &str, depth: usize) -> Result<String> {
    if depth > 4 {
        bail!("readme: include nesting deeper than 4");
    }
    let mut out = String::new();
    for line in src.lines() {
        if let Some(name) = directive(line, "include:") {
            let fragment = read(&root.join(SRC_DIR).join(name))?;
            out.push_str(&expand_includes(
                root,
                strip_leading_comment(&fragment),
                depth + 1,
            )?);
        } else {
            out.push_str(line);
            out.push('\n');
        }
    }
    Ok(out)
}

/// `<!-- KEY rest -->` → `Some(rest)` for a line consisting of that comment only.
fn directive<'a>(line: &'a str, key: &str) -> Option<&'a str> {
    let inner = line
        .trim()
        .strip_prefix("<!--")?
        .strip_suffix("-->")?
        .trim();
    inner.strip_prefix(key).map(str::trim)
}

/// Drop a leading `<!-- … -->` block (authoring notes in sources and fragments).
fn strip_leading_comment(src: &str) -> &str {
    let trimmed = src.trim_start();
    if trimmed.starts_with("<!--") {
        if let Some(end) = trimmed.find("-->") {
            let rest = &trimmed[end + 3..];
            // Directives are single-line comments; only strip a multi-line note.
            if trimmed[..end].contains('\n') {
                return rest.strip_prefix('\n').unwrap_or(rest);
            }
        }
    }
    src
}

fn render(template: &str, channel: &str, facts: &[(&'static str, String)]) -> Result<String> {
    let body = select_channel(strip_leading_comment(template), channel)?;
    let mut text = body;
    for (key, value) in facts {
        text = text.replace(&format!("{{{{{key}}}}}"), value);
    }
    if let Some(unknown) = find_unknown_placeholder(&text) {
        bail!("readme: unknown placeholder {{{{{unknown}}}}} in the {channel} README");
    }
    if channel != "github" {
        text = absolutize_links(&text);
    }
    Ok(format!("{GENERATED_HEADER}{}", tidy(&text)))
}

/// Keep lines outside `<!-- only: … -->` blocks, and inside the ones naming `channel`.
fn select_channel(src: &str, channel: &str) -> Result<String> {
    let mut stack: Vec<bool> = Vec::new();
    let mut out = String::new();
    for (no, line) in src.lines().enumerate() {
        if let Some(list) = directive(line, "only:") {
            if !list
                .split_whitespace()
                .all(|c| CHANNELS.iter().any(|(n, _)| *n == c))
            {
                bail!(
                    "readme: line {}: unknown channel in `{}`",
                    no + 1,
                    line.trim()
                );
            }
            stack.push(list.split_whitespace().any(|c| c == channel));
            continue;
        }
        if directive(line, "/only").is_some() {
            if stack.pop().is_none() {
                bail!(
                    "readme: line {}: `<!-- /only -->` without an opening block",
                    no + 1
                );
            }
            continue;
        }
        if stack.iter().all(|keep| *keep) {
            out.push_str(line);
            out.push('\n');
        }
    }
    if !stack.is_empty() {
        bail!("readme: unclosed `<!-- only: … -->` block");
    }
    Ok(out)
}

/// A `{{lower_snake}}` token left after substitution is a typo in the source.
/// (`{{SemiFlow}}` in BibTeX is not a placeholder: placeholders are lowercase.)
fn find_unknown_placeholder(text: &str) -> Option<&str> {
    let mut rest = text;
    while let Some(start) = rest.find("{{") {
        let after = &rest[start + 2..];
        if let Some(end) = after.find("}}") {
            let name = &after[..end];
            if !name.is_empty()
                && name
                    .chars()
                    .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '_')
            {
                return Some(name);
            }
        }
        rest = after;
    }
    None
}

/// `](relative/path)` → `](https://github.com/…/blob/master/relative/path)`.
fn absolutize_links(text: &str) -> String {
    let mut out = String::with_capacity(text.len());
    let mut rest = text;
    while let Some(pos) = rest.find("](") {
        out.push_str(&rest[..pos + 2]);
        rest = &rest[pos + 2..];
        let is_relative = !(rest.starts_with("http://")
            || rest.starts_with("https://")
            || rest.starts_with('#')
            || rest.starts_with("mailto:"));
        if is_relative {
            out.push_str(REPO_BLOB);
            rest = rest.strip_prefix("./").unwrap_or(rest);
        }
    }
    out.push_str(rest);
    out
}

/// Collapse runs of blank lines and end with exactly one newline.
fn tidy(text: &str) -> String {
    let mut out = String::new();
    let mut blank_run = 0;
    for line in text.trim().lines() {
        if line.trim().is_empty() {
            blank_run += 1;
            if blank_run > 1 {
                continue;
            }
        } else {
            blank_run = 0;
        }
        out.push_str(line.trim_end());
        out.push('\n');
    }
    out
}

// ---------------------------------------------------------------------------
// Facts computed from the manifests and sources
// ---------------------------------------------------------------------------

fn collect_facts(root: &Path) -> Result<Vec<(&'static str, String)>> {
    let workspace = read(&root.join("Cargo.toml"))?;
    let core = read(&root.join("crates/semiflow/Cargo.toml"))?;
    let version = toml_value(&workspace, "workspace.package", "version")?;
    let msrv = toml_value(&workspace, "workspace.package", "rust-version")?;
    let deps = toml_keys(&core, "dependencies");
    let py_functions = python_functions(root)?;
    let (lite, full) = wasm_classes(root)?;
    Ok(vec![
        ("pep440_version", pep440(&version)),
        ("version", version),
        ("msrv", msrv),
        ("runtime_dep_count", deps.len().to_string()),
        ("runtime_deps", backticked(&deps)),
        ("features_table", features_table(root, &core)?),
        ("py_class_count", python_class_count(root)?.to_string()),
        (
            "py_functions",
            backticked(
                &py_functions
                    .iter()
                    .map(|f| format!("{f}()"))
                    .collect::<Vec<_>>(),
            ),
        ),
        ("wasm_lite_table", class_table(&lite)),
        ("wasm_full_table", class_table(&full)),
    ])
}

fn backticked(items: &[String]) -> String {
    items
        .iter()
        .map(|i| format!("`{i}`"))
        .collect::<Vec<_>>()
        .join(", ")
}

/// Lines of the `[section]` table (up to the next `[…]` header).
fn toml_section<'a>(src: &'a str, section: &str) -> Vec<&'a str> {
    let header = format!("[{section}]");
    src.lines()
        .skip_while(|l| l.trim() != header)
        .skip(1)
        .take_while(|l| !l.trim_start().starts_with('['))
        .collect()
}

fn toml_value(src: &str, section: &str, key: &str) -> Result<String> {
    toml_section(src, section)
        .into_iter()
        .find_map(|l| {
            let (k, v) = l.split_once('=')?;
            (k.trim() == key).then(|| {
                v.split('#')
                    .next()
                    .unwrap_or("")
                    .trim()
                    .trim_matches('"')
                    .to_owned()
            })
        })
        .with_context(|| format!("readme: `{key}` not found in [{section}]"))
}

fn toml_keys(src: &str, section: &str) -> Vec<String> {
    toml_section(src, section)
        .into_iter()
        .filter_map(|l| {
            let l = l.trim();
            if l.is_empty() || l.starts_with('#') {
                return None;
            }
            l.split_once('=').map(|(k, _)| k.trim().to_owned())
        })
        .collect()
}

/// `0.13.1-beta` → `0.13.1b0`, `1.0.0-rc.2` → `1.0.0rc2` (PEP 440, as maturin does).
fn pep440(version: &str) -> String {
    let Some((base, pre)) = version.split_once('-') else {
        return version.to_owned();
    };
    let (label, num) = pre.split_once('.').unwrap_or((pre, "0"));
    let tag = match label {
        "alpha" | "a" => "a",
        "beta" | "b" => "b",
        "rc" => "rc",
        other => other,
    };
    format!("{base}{tag}{num}")
}

/// The feature table: names and defaults from Cargo.toml, prose from features.md.
fn features_table(root: &Path, core_manifest: &str) -> Result<String> {
    let section = toml_section(core_manifest, "features");
    let mut defaults = BTreeSet::new();
    let mut names = BTreeSet::new();
    for line in section {
        let Some((k, v)) = line.split_once('=') else {
            continue;
        };
        let k = k.trim();
        if k.starts_with('#') {
            continue;
        }
        if k == "default" {
            let list = v.split('#').next().unwrap_or("");
            for item in list
                .trim()
                .trim_start_matches('[')
                .trim_end_matches(']')
                .split(',')
            {
                let item = item.trim().trim_matches('"');
                if !item.is_empty() {
                    defaults.insert(item.to_owned());
                }
            }
        } else {
            names.insert(k.to_owned());
        }
    }

    let doc = read(&root.join(SRC_DIR).join("features.md"))?;
    let mut rows = Vec::new();
    let mut described = BTreeSet::new();
    for line in doc.lines().filter(|l| l.starts_with("| `")) {
        let cells: Vec<&str> = line.trim_matches('|').split('|').map(str::trim).collect();
        let [name, desc] = cells[..] else {
            bail!("readme: features.md: expected `| `name` | description |`: {line}");
        };
        let name = name.trim_matches('`');
        described.insert(name.to_owned());
        let default = if defaults.contains(name) { "yes" } else { "no" };
        rows.push(format!("| `{name}` | {default} | {desc} |"));
    }
    if described != names {
        bail!(
            "readme: docs/readme/features.md and crates/semiflow/Cargo.toml disagree.\n  \
             only in Cargo.toml: {:?}\n  only in features.md: {:?}",
            names.difference(&described).collect::<Vec<_>>(),
            described.difference(&names).collect::<Vec<_>>()
        );
    }
    Ok(format!(
        "| Feature | Default | Effect |\n|---------|---------|--------|\n{}",
        rows.join("\n")
    ))
}

/// Distinct `#[pyclass(name = "…")]` registrations (the Python-visible classes).
fn python_class_count(root: &Path) -> Result<usize> {
    let mut names = BTreeSet::new();
    for path in rust_files(&root.join("crates/semiflow-py/src"))? {
        let src = read(&path)?;
        for line in src.lines().filter(|l| l.contains("pyclass(")) {
            if let Some(rest) = line.split("name").nth(1) {
                if let Some(name) = rest.split('"').nth(1) {
                    names.insert(name.to_owned());
                }
            }
        }
    }
    Ok(names.len())
}

/// Module-level functions declared in the shipped `__init__.pyi` stub.
fn python_functions(root: &Path) -> Result<Vec<String>> {
    let stub = read(&root.join("crates/semiflow-py/python/semiflow/__init__.pyi"))?;
    Ok(stub
        .lines()
        .filter_map(|l| l.strip_prefix("def "))
        .filter_map(|l| l.split('(').next())
        .map(str::to_owned)
        .collect())
}

fn rust_files(dir: &Path) -> Result<Vec<PathBuf>> {
    let mut files = Vec::new();
    for entry in walkdir::WalkDir::new(dir) {
        let entry = entry?;
        if entry.path().extension().is_some_and(|e| e == "rs") {
            files.push(entry.into_path());
        }
    }
    files.sort();
    Ok(files)
}

/// `(js_name, first doc line)` of every exported WASM class, split into the
/// default npm build and the `full`-feature build.
type ClassList = Vec<(String, String)>;

fn wasm_classes(root: &Path) -> Result<(ClassList, ClassList)> {
    let src_dir = root.join("crates/semiflow-wasm/src");
    let lib = read(&src_dir.join("lib.rs"))?;
    let lines: Vec<&str> = lib.lines().collect();
    let mut full_modules = BTreeSet::new();
    for pair in lines.windows(2) {
        if pair[0].trim() == "#[cfg(feature = \"full\")]" {
            if let Some(m) = pair[1].trim().strip_prefix("mod ") {
                full_modules.insert(m.trim_end_matches(';').to_owned());
            }
        }
    }

    // A file spliced in with `include!("x.rs")` inherits the gate of its includer.
    let files = rust_files(&src_dir)?;
    for path in &files {
        let stem = file_stem(path);
        if full_modules.contains(&stem) {
            for line in read(path)?.lines() {
                if let Some(inc) = line.trim().strip_prefix("include!(\"") {
                    full_modules.insert(
                        inc.trim_end_matches("\");")
                            .trim_end_matches(".rs")
                            .to_owned(),
                    );
                }
            }
        }
    }

    let (mut lite, mut full) = (Vec::new(), Vec::new());
    for path in &files {
        let target = if full_modules.contains(&file_stem(path)) {
            &mut full
        } else {
            &mut lite
        };
        target.extend(wasm_exports(&read(path)?));
    }
    lite.sort();
    full.sort();
    Ok((lite, full))
}

fn file_stem(path: &Path) -> String {
    path.file_stem()
        .and_then(|s| s.to_str())
        .unwrap_or_default()
        .to_owned()
}

/// Column-0 `#[wasm_bindgen…]` directly above `pub struct X`.
fn wasm_exports(src: &str) -> ClassList {
    let lines: Vec<&str> = src.lines().collect();
    let mut out = Vec::new();
    for (i, line) in lines.iter().enumerate() {
        if !line.starts_with("#[wasm_bindgen") || line.contains("js_class") {
            continue;
        }
        let Some(next) = lines[i + 1..].iter().find(|l| !l.trim().is_empty()) else {
            continue;
        };
        let Some(rest) = next.trim().strip_prefix("pub struct ") else {
            continue;
        };
        let struct_name: String = rest
            .chars()
            .take_while(|c| c.is_alphanumeric() || *c == '_')
            .collect();
        let js_name = line
            .split("js_name")
            .nth(1)
            .and_then(|r| r.split('"').nth(1))
            .map_or(struct_name, str::to_owned);
        out.push((js_name, doc_summary(&lines[..i])));
    }
    out
}

/// First paragraph of the `///` block right above the attribute, without the
/// internal cross-references (ADR / § / milestone / internal version tags).
fn doc_summary(before: &[&str]) -> String {
    let mut block: Vec<&str> = before
        .iter()
        .rev()
        .take_while(|l| l.trim_start().starts_with("///") || l.trim_start().starts_with("#["))
        .filter(|l| l.trim_start().starts_with("///"))
        .map(|l| l.trim_start().trim_start_matches("///").trim())
        .collect();
    block.reverse();
    let paragraph: Vec<&str> = block
        .into_iter()
        .skip_while(|l| l.is_empty())
        .take_while(|l| !l.is_empty() && !l.starts_with('#') && !l.starts_with("```"))
        .collect();
    let text = paragraph.join(" ").replace("[`", "`").replace("`]", "`");
    let cleaned = strip_internal_refs(&text);
    let cleaned = cleaned.trim().trim_end_matches([':', ',']).trim();
    cleaned.replace('|', "\\|")
}

/// Drop parenthesised items such as `ADR-0138`, `§21.9`, `math §50`, `M11`,
/// `Wave F`, `v8.3.0` and bare internal version tags like `v9.0.0-beta`.
fn strip_internal_refs(text: &str) -> String {
    fn internal(item: &str) -> bool {
        let item = item.trim();
        let versioned = |s: &str| {
            s.strip_prefix('v')
                .is_some_and(|r| r.chars().next().is_some_and(|c| c.is_ascii_digit()))
        };
        item.starts_with("ADR-")
            || item.starts_with('§')
            || item.starts_with("math §")
            || item.starts_with("Wave ")
            || versioned(item)
            || (item.starts_with('M')
                && item.len() > 1
                && item[1..].chars().all(|c| c.is_ascii_digit()))
    }
    let mut out = String::new();
    let mut rest = text;
    while let Some(open) = rest.find('(') {
        out.push_str(&rest[..open]);
        let Some(close) = rest[open..].find(')') else {
            out.push_str(&rest[open..]);
            return out;
        };
        let inner = &rest[open + 1..open + close];
        let kept: Vec<&str> = inner
            .split(',')
            .filter(|i| !internal(i))
            .map(str::trim)
            .collect();
        if !kept.is_empty() {
            out.push('(');
            out.push_str(&kept.join(", "));
            out.push(')');
        } else {
            // drop the space that preceded the removed group
            while out.ends_with(' ') {
                out.pop();
            }
        }
        rest = &rest[open + close + 1..];
    }
    out.push_str(rest);
    // bare tags outside parentheses, e.g. "evaluator v8.1.0 for"
    out.split(' ')
        .filter(|w| {
            !(w.starts_with('v')
                && w[1..].chars().next().is_some_and(|c| c.is_ascii_digit())
                && w.contains('.'))
        })
        .collect::<Vec<_>>()
        .join(" ")
}

fn class_table(classes: &ClassList) -> String {
    let mut out = String::from("| Class | Description |\n|-------|-------------|\n");
    for (name, desc) in classes {
        out.push_str(&format!("| `{name}` | {desc} |\n"));
    }
    out.trim_end().to_owned()
}

// ---------------------------------------------------------------------------
// Executable README examples (Node.js)
// ---------------------------------------------------------------------------

/// Run every ```js block of the npm README (except `<!-- readme-test: skip` ones)
/// with Node.js, resolving `@semiflow/wasm` to the built package in `args[0]`.
pub fn run_js_examples(args: &[String]) -> Result<()> {
    let root = crate::workspace_root()?;
    let Some(pkg) = args.first() else {
        bail!("usage: cargo xtask readme-examples-js <built-package-dir, e.g. dist/npm>");
    };
    let pkg = fs::canonicalize(root.join(pkg)).with_context(|| format!("package dir {pkg}"))?;
    let readme = read(&root.join("crates/semiflow-wasm/README.md"))?;
    let blocks = code_blocks(&readme, "js");
    let work = root.join("target").join("readme-examples");
    fs::create_dir_all(&work)?;

    let mut ran = 0;
    for (i, block) in blocks.iter().enumerate() {
        let script = block.replace(
            "require('@semiflow/wasm')",
            &format!("require({:?})", pkg.display().to_string()),
        );
        let file = work.join(format!("example-{i}.cjs"));
        fs::write(&file, script)?;
        let status = process::Command::new("node").arg(&file).status()?;
        if !status.success() {
            bail!(
                "readme-examples-js: example {i} failed ({})",
                file.display()
            );
        }
        ran += 1;
    }
    if ran == 0 {
        bail!("readme-examples-js: no runnable ```js blocks found");
    }
    println!("readme-examples-js: PASS — {ran} example(s)");
    Ok(())
}

/// Bodies of fenced ```lang blocks not preceded by a `readme-test: skip` marker.
pub fn code_blocks(markdown: &str, lang: &str) -> Vec<String> {
    let mut blocks = Vec::new();
    // Some((keep, body)) while inside a ```lang block.
    let mut current: Option<(bool, String)> = None;
    let mut skip_next = false;
    for line in markdown.lines() {
        if let Some((keep, body)) = current.as_mut() {
            if line.trim_start().starts_with("```") {
                if *keep {
                    blocks.push(std::mem::take(body));
                }
                current = None;
            } else {
                body.push_str(line);
                body.push('\n');
            }
        } else if line.contains("<!-- readme-test: skip") {
            skip_next = true;
        } else if line.trim_start().strip_prefix("```") == Some(lang) {
            current = Some((!skip_next, String::new()));
            skip_next = false;
        } else if !line.trim().is_empty() {
            skip_next = false;
        }
    }
    blocks
}
